name: CI

run-name: CI[${{ github.run_number }}] ${{ github.ref_name }} (by ${{ github.actor }})

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  format-check:
    name: format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install packages
        run: npm ci

      - name: execute task
        run: npx nx format:check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install packages
        run: npm ci

      - name: execute task
        run: npx nx affected -t lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install packages
        run: npm ci

      - name: execute task
        run: npx nx affected -t test
